// Requires macOS's Samantha voice and ffmpeg. Run again after editing cues.
import { readFileSync, writeFileSync, mkdirSync, mkdtempSync, rmSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { flattenRoutine, speechForStep } from "../js/session.js";

const root = fileURLToPath(new URL("../", import.meta.url));
const { routines } = JSON.parse(readFileSync(join(root, "routines.json"), "utf8"));
const texts = new Set();
for (const routine of routines) {
  const steps = flattenRoutine(routine);
  steps.forEach((step, i) => {
    texts.add(speechForStep(step, steps[i - 1]));
    texts.add(speechForStep(step, null)); // Full instructions for replay/resume.
  });
}
const output = join(root, "audio");
mkdirSync(output, { recursive: true });
const temp = mkdtempSync(join(tmpdir(), "down-dog-voice-"));
const manifest = {};
try {
  // The chime and speech share a file, so there is no delayed speech race.
  const rate = 22050;
  const samples = Math.ceil(rate * 0.8);
  const wav = Buffer.alloc(44 + samples * 2);
  wav.write("RIFF", 0); wav.writeUInt32LE(wav.length - 8, 4);
  wav.write("WAVEfmt ", 8); wav.writeUInt32LE(16, 16);
  wav.writeUInt16LE(1, 20); wav.writeUInt16LE(1, 22);
  wav.writeUInt32LE(rate, 24); wav.writeUInt32LE(rate * 2, 28);
  wav.writeUInt16LE(2, 32); wav.writeUInt16LE(16, 34);
  wav.write("data", 36); wav.writeUInt32LE(samples * 2, 40);
  for (let i = 0; i < samples; i++) {
    const t = i / rate;
    let value = 0;
    for (const [freq, amplitude, delay] of [[523.25, 0.22, 0], [659.25, 0.14, 0.03], [784, 0.1, 0.07]]) {
      const dt = t - delay;
      if (dt >= 0) value += Math.sin(2 * Math.PI * freq * dt) * amplitude * Math.min(1, dt / 0.02) * Math.exp(-8 * dt);
    }
    wav.writeInt16LE(Math.round(value * 32767), 44 + i * 2);
  }
  writeFileSync(join(temp, "chime.wav"), wav);
  for (const text of texts) {
    const id = createHash("sha256").update(text).digest("hex").slice(0, 12);
    const file = `${id}.m4a`;
    const voiceFile = join(temp, "voice.aiff");
    execFileSync("say", ["-v", "Samantha", "-r", "150", "-o", voiceFile, text]);
    if (statSync(voiceFile).size <= 4096) throw new Error("Speech engine produced no samples. Run with access to the macOS speech service.");
    execFileSync("ffmpeg", ["-hide_banner", "-loglevel", "error", "-y", "-i", join(temp, "chime.wav"), "-i", voiceFile,
      "-filter_complex", "[1:a]adelay=650[voice];[0:a][voice]amix=inputs=2:duration=longest:normalize=0[out]",
      "-map", "[out]", "-c:a", "aac", "-b:a", "64k", "-movflags", "+faststart", resolve(output, file)]);
    manifest[text] = `./audio/${file}`;
  }
  writeFileSync(join(root, "js/cues.js"), `// Generated by scripts/build_audio.mjs.\nexport const CUES = ${JSON.stringify(manifest, null, 2)};\n`);
  console.log(`Built ${texts.size} chime + voice recordings.`);
} finally {
  rmSync(temp, { recursive: true, force: true });
}
