import { writeFileSync } from "node:fs";
import { CUES } from "../js/cues.js";
import { POSE_URLS } from "../js/poses.js";

writeFileSync(new URL("../js/offline-assets.js", import.meta.url),
  `// Generated by scripts/build_offline.mjs.\nself.OFFLINE_MEDIA = ${JSON.stringify([...POSE_URLS, ...new Set(Object.values(CUES))], null, 2)};\n`);
